# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-15 09:50
from __future__ import unicode_literals

from django.db import migrations, models
import pyuploadcare.dj.models


class Migration(migrations.Migration):

    dependencies = [
        ('collect', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Projects',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('image', pyuploadcare.dj.models.ImageField()),
                ('decription', models.TextField(max_length=200)),
                ('link', models.URLField(blank=True, default='', null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='profile',
            name='contact',
            field=models.CharField(max_length=30),
        ),
    ]
