# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-18 21:17
from __future__ import unicode_literals

from django.db import migrations
import pyuploadcare.dj.models


class Migration(migrations.Migration):

    dependencies = [
        ('collect', '0005_auto_20181017_0808'),
    ]

    operations = [
        migrations.AddField(
            model_name='projects',
            name='image2',
            field=pyuploadcare.dj.models.ImageField(null=True),
        ),
        migrations.AddField(
            model_name='projects',
            name='image3',
            field=pyuploadcare.dj.models.ImageField(null=True),
        ),
    ]
